name: Hibaullahi Shakira

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write # Consider removing if not needed for OIDC

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Build Project
        run: npm install && npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: 'static-files' # Added a name to the artifact (recommended)
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact: static-files # Specify the artifact to deploy (important!)